cluster:
  k8sVersion: "1.24" # currently 1.18, 1.19, 1.20, 1.21, 1.22 and 1.23 are supported
  name: "otomi-cluster" # the name of your cluster
  provider: "digitalocean" # choose between aws, azure, google, digitalocean or custom

otomi:
  version: "main"
